### ISSUE TITLE
Typedoc introduced breaking change starting version 0.21.0

### ISSUE THREAD

**Issue by Dynacord** [kamiazya/typedoc-plugin-mermaid#354]
**Describe the bug**
Typedoc has changed the way they load plugins, breaking the existing plugins

**To Reproduce**
1. Install the latest version of typedoc

**Expected behavior**
Plugin should load correctly

**Comment by Dynacord** [comment]
Thanks a lot !

**Comment by kamiazya** [comment]
@Dynacord Thanks for reporting issue!

This issue fixed in [v1.4.0](https://github.com/kamiazya/typedoc-plugin-mermaid/releases/tag/v1.4.0).

**Comment by kamiazya** [comment]
@all-contributors please add @Dynacord  for bug.
