### ISSUE TITLE
Mermaid 8.8.1 introduced a visual regression

### ISSUE THREAD

**Issue by thegiantbeast** [kamiazya/typedoc-plugin-mermaid#468]
**Describe the bug**
Just want to bring to your attention that mermaid `8.8.1` brought a visual regression described [here](https://github.com/mermaid-js/mermaid/issues/1984#issuecomment-963209181), where basically leaves a huge top and bottom whitespace.

I guess this needs to be fixed at mermaid level but wanted to shared with the others if they ever face the same issue and not spending the time for finding the problem.

The current workaround would be to change the `unpkg.com` url from `https://unpkg.com/mermaid/dist/mermaid.min.js` to `https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js`.

**Comment by thegiantbeast** [comment]
Forgot to relate with the mermaid issue: https://github.com/mermaid-js/mermaid/issues/1984

**Comment by thegiantbeast** [comment]
@kamiazya also, wouldn't it be better to somehow lock it into a version range? I'm just thinking that if mermaid decides to release a breaking change version, this will be picked up as the latest version and potentially break everyone code.

**Comment by kamiazya** [comment]
@thegiantbeast 
Thank you for reporting!


If this plugin locks the version of mermaid, it is necessary to release plugin for each version upgrade of mermaid, and I'm afraid that the maintenance cost will increase.

I want to allow users to specify any mermaid version while maintaining the specification to use the latest mermaid version as a plugin.

How about this idea?

**Comment by thegiantbeast** [comment]
@kamiazya that sounds great, so it gives the flexibility to specify the version for critical things and let it use the latest if not specified.

I will see if I find some time to open a PR for it.

**Comment by kamiazya** [comment]
@thegiantbeast 

Perhaps `addDeclaration` method of the Options class is useful.

https://typedoc.org/api/classes/Options.html

I'm waiting for PR.
