### ISSUE TITLE
Sequence diagram misses arrows

### ISSUE THREAD

**Issue by guryanovev** [kamiazya/typedoc-plugin-mermaid#541]
**Describe the bug**
Sequence diagrams do not display any arrows when rendered

**To Reproduce**
1. Just try rendering sample sequence diagram

````
sequenceDiagram
    Alice->>+John: Hello John, how are you?
    Alice->>+John: John, can you hear me?
    John-->>-Alice: Hi Alice, I can hear you!
    John-->>-Alice: I feel great!
````

**Expected behavior**
Arrows should display according to the mermaid syntax

**Screenshots**
![image](https://user-images.githubusercontent.com/2764795/154333996-cceea043-fcd2-42df-adbf-72eb28d397ba.png)

**Additional context**

The reason is probably the fact that there are 2 versions rendered: light and dark

![image](https://user-images.githubusercontent.com/2764795/154334627-1079d16e-0490-46af-abdb-8b2e03360452.png)

And arrows markers are referenced by id:

![image](https://user-images.githubusercontent.com/2764795/154334759-5ae95127-94b2-44fa-af4d-53b0d5740868.png)

So id's got duplicated and light-theme svg tries to display markers from dark-theme svg

**Comment by kamiazya** [comment]
Thank you for the report.

This is an issue managed by the mermaid.js project, so I close this issue.

https://github.com/mermaid-js/mermaid/issues/1871

**Comment by kamiazya** [comment]
@all-contributors please add @guryanovev  for bugs.

**Comment by Kesshi** [comment]
The issue https://github.com/mermaid-js/mermaid/issues/1871 is fixed now but i still see the same issue using this plugin. Maybe the plugin styles https://github.com/kamiazya/typedoc-plugin-mermaid/blob/main/src/plugin.ts#L5 have to updated as well?

**Comment by coreyward** [comment]
Seeing this still with the latest Mermaid and typedoc-plugin-mermaid versions.
