### ISSUE TITLE
Issues with TypeDoc 0.25.x

### ISSUE THREAD

**Issue by ludovicm67** [kamiazya/typedoc-plugin-mermaid#777]
**Describe the bug**
I upgraded to TypeDoc 0.25.x on my project, and the rendering of the mermaid graph I have on my README.md file is not working anymore.
It was working well with previous versions.

**Expected behavior**
The mermaid graph on the README.md file should be rendered.

**Additional context**
I'm using the latest version of `typedoc-plugin-mermaid`.

It is working as expected with 0.23.x and 0.24.x TypeDoc versions.

When I run TypeDoc, it's also showing the following line in the console:
> Loaded plugin typedoc-plugin-mermaid

Which is not the case anymore with 0.25.x.

**Comment by michal-kindl** [comment]
Hi, 
TypeDoc 0.25.x seems to have deactiavated automatic plugin loading. You have to start TypeDoc with --plugin your-plugin-name parameter.
[TypeDoc Plugin Docs](https://typedoc.org/guides/plugins/#0.25.4)
As in my case had worked: 
`typedoc --plugin typedoc-plugin-mermaid`

**Comment by ludovicm67** [comment]
Hi @michal-kindl,

Thanks for your comment here!
Using the `--plugin` parameter, it's able to load the plugin as expected.

But this will have side effects for people using multiple plugins, as they will not be loaded anymore if they use that `--plugin` parameter, according to point 2. from the documentation here: https://typedoc.org/guides/development/#high-level:

```
TypeDoc follows several high level steps when called.

1. Read options
   Necessary to determine which plugins should be loaded.
2. Load plugins
   If --plugin was used, loads only those specified plugins, otherwise loads all npm plugins with the typedocplugin keyword.
3. Read options again to pick up plugin options
4. Convert the input files into the models (also called reflections) that live under src/lib/models
5. Resolve the models
   Necessary to handle links to models that might not have been created when the source model is generated.
6. Output the models by serializing to HTML and/or JSON
```

So the workaround would be to specify all plugins manually.

Is there a way to enable autoloading of this plugin, or is it an upstream issue?

At least, changelogs of TypeDoc itself don't tell anything about removing the autoload part.

**Comment by michal-kindl** [comment]
Hi @ludovicm67,
I absolutely agree, that it causes problems with more plugins. As I followed your link from TypeDoc docs, there is also documentation inconsistence. Here is another statement, saying that no plugins are loaded by default since 0.24...

[TypeDoc Documentation, see section "plugin"](https://typedoc.org/options/configuration/#plugin)

**Comment by kamiazya** [comment]
@ludovicm67 @michal-kindl 

Thanks for the report.
We have recently described the required support in the README as well in #856 and released it in [v1.11.0](https://github.com/kamiazya/typedoc-plugin-mermaid/releases/tag/typedoc-plugin-mermaid%401.11.0).

We will close this issue.

**Comment by kamiazya** [comment]
@all-contributors please add @ludovicm67  for a11y. please add @michal-kindl  for a11y.

**Comment by kamiazya** [comment]
@all-contributors please add @michal-kindl  for a11y.
